In [ ]:
import numpy as np
#single value decomposition

a=np.array([[3,4],[5,7]])
print("Matrix is:")
print(a)
m,n,p=np.linalg.svd(a)
print("single value decomposition of Array:")
print()
print(m)
print()
print(n)
print()
print(p)

#remake

print("Remake")
b=(m@np.diag(n)@p)
print(b)

Matrix is:
[[3 4]
 [5 7]]
single value decomposition of Array:

[[-0.50246864 -0.86459543]
 [-0.86459543  0.50246864]]

[9.94936671 0.10050891]

[[-0.58600545 -0.81030711]
 [-0.81030711  0.58600545]]
Remake
[[3. 4.]
 [5. 7.]]
