In [ ]:
import numpy as np
print("SVD")
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("MAtrix A=\n",a)

SVD
MAtrix A=
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
U,D,VT=np.linalg.svd(a)
print("U\n",U)

U
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]


In [ ]:
print("D",D)

D [1.68481034e+01 1.06836951e+00 4.41842475e-16]


In [ ]:
print("VT",VT)

VT [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [ ]:
print("\nRemake")
ar=(U@np.diag(D)@VT)
print(ar)


Remake
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
